version: "3.7"
services:
  web:
    image: greencheck
    # command: bash -c './wait-for db:3306 -- ./runtests.sh'
    # volumes:
    #   - type: bind
    #     source: ./packages/greencheck
    #     target: /app

    links:
      - redis
      - db

  redis:
    image: redis:alpine

  db:
    image: circleci/mysql:5.6
