version: "3.7"
services:
  web:
    image: gcr.io/prodsci-tgwf-0/greencheck
    # uncomment this to mount the greencheck code
    # so you don't need to rebuild the image on each change
    # volumes:
    #   - type: bind
    #     source: ./packages/greencheck
    #     target: /app
    environment:
      TGWF_CONFIG_FILE_PATH: /config.ci.yml

    links:
      - redis
      - db

  redis:
    image: redis:alpine

  db:
    image: circleci/mysql:5.6
